export const GET_POSTS_TO_USER_REQUEST = 'GET_POSTS_TO_USER_REQUEST';
export const GET_POSTS_TO_USER_SUCCESS = 'GET_POSTS_TO_USER_SUCCESS';
export const GET_POSTS_TO_USER_ADD = 'GET_POSTS_TO_USER_ADD';
export const GET_POSTS_TO_USER_ERROR = 'GET_POSTS_TO_USER_ERROR';

export const GET_POSTS_ALL_REQUEST = 'GET_POSTS_ALL_REQUEST';
export const GET_POSTS_ALL_SUCCESS = 'GET_POSTS_ALL_SUCCESS';
export const GET_POSTS_ALL_ADD = 'GET_POSTS_ALL_ADD';
export const GET_POSTS_ALL_ERROR = 'GET_POSTS_ALL_ERROR';